server:
  port:
    8081
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres


